name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: luau-execution
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@d49be92bd9502180218c3f43e7988faa945217b0 # v0.1.2

      - name: Compile
        run: pnpm prod:build

      - name: Run tests
        run: lune run tests/init.luau
        env:
          ROBLOX_OC_API_KEY: ${{ secrets.JEST_TEST_API_KEY}}
          ROBLOX_UNIVERSE_ID: ${{ vars.ROBLOX_TEST_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ vars.ROBLOX_TEST_PLACE_ID }}
          TEST_TASK_FILE: dist/test/runtime.server.luau
          